# Don't print a new line at the start of the prompt
add_newline = false

# Use custom format
format = """
 $directory\
	${custom.git_status}\
	$package\
		$rust$python\
	$cmd_duration
 $character
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Package Version Config
[package]
format = " via [ğŸ $version](208 bold) "

[character]
success_symbol = "[Î»]($bold green)"
error_symbol = "[Î»]($bold fg:#fd6f6b)"

[directory]
disabled = false
read_only = "ğŸ”’ "
read_only_style = "red"
truncate_to_repo = false
truncation_length = 8
format = "[$read_only]($read_only_style)[$path](bold fg:#94bdff)"

[custom.git_status]
description = "git status which calls git directly"
command = "~/.dotfiles/zshrc/starship/gitstatus.zsh || true"
when = "true"
style = "bold red"
# current master version of how to specify formats
format = "[$output]($style) "
#disabled = true

# Language Support
[python]
format = "ğŸ "

[rust]
format = "ğŸ¦€ "
